baseurl = "http://dangdangdotcom.github.io/elastic-job/"
languageCode = "en-us"
title = "Elastic-Job"

[params]
    description = "Elastic-Job - distributed scheduled job solution"
    author_url = "https://github.com/dangdangdotcom"
    project_url = "https://github.com/dangdangdotcom/elastic-job"
    project_documentation = "http://dangdangdotcom.github.io/elastic-job"
    github_project_name = "Elastic-Job"
    github_user_name = "dangdangdotcom"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
